name: aphorica_dartutils
description: various html and svg dom utilities
version: 0.1.0
#homepage: https://www.example.com
#author: Rick Berger <rickb@aphorica.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
